### ISSUE TITLE
Tie breaking behavior?

### ISSUE THREAD

**Issue by mhkeller** [gmac/constellation-js#2]
It seems if I have a uniform grid and a lot of points, the page often comes back saying the script is unresponsive. If I add some noise to my grid this doesn't happen. Is there any default tie breaking behavior that might be the cause of this? I can put up a demo if that would help.

**Comment by gmac** [comment]
preferred path selection is included in the v2 rewrite, https://github.com/gmac/constellation-js/compare/v2?expand=1#diff-b8a943f2b67629cb3ff1f2c70189c0bc9df6056e96b7ee5c321aa3f2fd98a34eR231.
